import { createTheme } from "@rneui/themed";

export const lightTheme = createTheme({
  lightColors: {
    background: "#FFFFFF",
    primary: "#F5F5F5",
    primaryText: "#000000",
    secondary: "#333333",
    accentColor: "#A6A6A6",
    borderColor: "#E0E0E0",
    priceText: "#fdc500",
    buttonColor: "#ffd60a",
    error: "#ff5252",
    infoColor: "#0d47a1",
    nextColor: "#0d47a1",
    infoTextColor: "white",
    themeLightColor: "#Ffff00",
    themeSelectedOption: "#D4D4D4",
    themeUnselectedOption: "#eff7fa",
    themeDarkIcon: "#87CEEB",
    tableHeaderBackground: "#F0F0F0",
    tableRowBackground: "#FFFFFF",
    tablePaginationBackground: "#FFFFFF",
    tableLabelBackground: "#333333",
    tableIconBackground: "#F5F5F5",
    dropdownColor: "#b8c0bb",
    statusPending: "#FFA500",
    statusPaymentPending: "#FFD700",
    statusShipped: "#1E90FF",
    statusCompleted: "#32CD32",
    statusCanceled: "#FF4500",
  },
  mode: "light",
});

export const darkTheme = createTheme({
  darkColors: {
    background: "#2C2C2C",
    primary: "#3A3A3A",
    primaryText: "#fff",
    secondary: "#B3B3B3",
    accentColor: "#444444",
    borderColor: "#444444",
    priceText: "#e6cc00",
    buttonColor: "#ffffa3",
    error: "#cf6679",
    infoColor: "#fcdd00",
    nextColor: "#0d47a1",
    infoTextColor: "white",
    themeLightColor: "#fdc500",
    themeSelectedOption: "#242526",
    themeUnselectedOption: "#3a3b3c",
    themeDarkIcon: "#87CEEB",
    tableHeaderBackground: "#3A3A3A",
    tableRowBackground: "#2C2C2C",
    tablePaginationBackground: "#3E3E3E",
    tableLabelBackground: "#CCCCCC",
    tableIconBackground: "#6A6A6A",
    dropdownColor: "#4b4c4e",
    statusPending: "#FFA500",
    statusPaymentPending: "#FFD700",
    statusShipped: "#1E90FF",
    statusCompleted: "#32CD32",
    statusCanceled: "#FF4500",
  },
  mode: "dark",
});
